### ISSUE TITLE
zsh: command not found: aeiva-chat-terminal

### ISSUE THREAD

**Issue by wyushi** [chatsci/Aeiva#3]
Installed via pip successfully. Verified the installation with 
```
~ python -c "import aeiva; print(aeiva.__version__)"
0.8.2
```

but got the cmd-not-found error when starting the terminal chat ai
```
aeiva-chat-terminal --config configs/agent_config.yaml --verbose
zsh: command not found: aeiva-chat-terminal
``` 
<img width="549" alt="Screenshot 2024-12-13 at 12 34 25 AM" src="https://github.com/user-attachments/assets/193a4fe6-a3ce-44a4-9adc-f4e522db9019" />

**Comment by chatsci** [comment]
The problem shall be fixed now.

1. reinstall the newest version via `pip install --upgrade aeiva`;
2. replace `configs/agent_config.yaml` with your own config file path. Note: you can find a template in the `example/` project. Create your yaml or json config file based on it.
3. You may need to further install some packages via `pip` or `brew` if you encountered any package errors.
4. To check logs, see the files in ~/.aeiva/log/
